window.runFixtureTests = async (options = {}) => {
  window.fixtureTestsDone=false;
  const results=window.fixtureTestResults=[];
  const flush=async()=>{await fixture.tick();await new Promise(requestAnimationFrame);await fixture.tick();};
  const check=(name,ok,detail)=>{results.push({name,pass:!!ok,detail});if(!ok)throw new Error(JSON.stringify(results));};
  const scroll=document.querySelector('.chat-scroll');
  const api=__KIMI_LAZY__;
  const action=detail=>window.dispatchEvent(new CustomEvent('kimi-lazy-action',{detail}));
  api.configure({auto:false});action('recent');await flush();
  if (options.allowLate && fixtureInitialCounts.mounts > 200)
    check('Via late injection unmounts excess native leaves',document.querySelectorAll('pre').length===200 && fixtureCounts.unmounts>=1300,{initial:fixtureInitialCounts,now:{...fixtureCounts}});
  else check('first render mounts only the requested heavy leaves',fixtureInitialCounts.mounts===200 && fixtureInitialCounts.unmounts===0,fixtureInitialCounts);
  const main=()=>api.stats().groups.find(s=>s.name==='ChatPane');
  check('latest 20 messages and per-message 20 blocks',main().counts[0].mounted===20 && document.querySelectorAll('pre').length===200,main().counts[0]);
  const old=document.querySelector('.kl-placeholder[data-turn-id="t1"]');
  old.click();await flush();
  check('restoring an old message uses native content',!!document.querySelector('.a-msg[data-turn-id="t1"]'),main().counts[0]);
  const head=document.querySelector('[data-turn-id="t1"] .ar-head');head.click();await flush();
  check('opening a 35-tool group mounts 20 tools',document.querySelectorAll('[data-turn-id="t1"] .ar-body pre').length===20,document.querySelectorAll('[data-turn-id="t1"] .ar-body pre').length);
  const block=document.querySelector('[data-turn-id="t1"] .ar-body .kl-placeholder');block.click();await flush();
  check('a tool block restores separately',document.querySelectorAll('[data-turn-id="t1"] .ar-body pre').length===21);
  const beforeClose=fixtureCounts.unmounts;head.click();await flush();
  check('closing a tool group unmounts its leaves',fixtureCounts.unmounts-beforeClose===21 && document.querySelectorAll('[data-turn-id="t1"] .ar-body pre').length===0);
  const restored=document.querySelector('[data-turn-id="t1"]');scroll.scrollTop=restored.offsetTop;await flush();
  api.sweep(Date.now()+600001);await flush();
  check('visible history survives timeout',!!document.querySelector('.a-msg[data-turn-id="t1"]'));
  scroll.scrollTop=scroll.scrollHeight;await flush();
  const before=fixtureCounts.unmounts;api.sweep(Date.now()+1200002);await flush();
  check('offscreen idle history is unmounted after ten minutes',!!document.querySelector('.kl-placeholder[data-turn-id="t1"]') && fixtureCounts.unmounts>before,fixtureCounts.unmounts-before);
  fixture.append();await flush();fixture.update();await flush();
  check('live turn limits old blocks and receives streaming delta',document.querySelectorAll('[data-turn-id="new1"] pre').length===20 && document.querySelector('[data-turn-id="new1"]').textContent.includes('STREAM DELTA') && fixture.turns.value.at(-1).blocks.length===41);
  fixture.active.value=false;await flush();action('all');await new Promise(r=>setTimeout(r,700));await flush();
  check('full history loading preserves virtualization',fixture.turns.value.length===52 && main().counts[0].mounted<52,main().counts[0]);
  const hash=JSON.stringify(fixture.turns.value);api.configure({enabled:false});await flush();
  check('disable restores all native content without altering data',document.querySelectorAll('.kl-placeholder').length===0 && document.querySelectorAll('.turn-anchor').length===52 && hash===JSON.stringify(fixture.turns.value));
  api.configure({enabled:true});await flush();fixture.switchSession();await flush();api.sweep();await flush();
  check('session change cleans old IDs and detached instances',document.querySelectorAll('[data-turn-id^="t"]').length===0 && main().counts[0].total===10 && api.stats().states<30,api.stats().states);
  const panelHost=document.getElementById('kimi-lazy-panel');
  const tg=panelHost.shadowRoot.getElementById('toggle'),bodyEl=panelHost.shadowRoot.getElementById('body');
  const pe=(type,x,y)=>tg.dispatchEvent(new PointerEvent(type,{pointerId:7,clientX:x,clientY:y,button:0,bubbles:true}));
  // Establish a known start even when a previous fixture run saved the top-left corner.
  const initial=panelHost.getBoundingClientRect();
  pe('pointerdown',initial.left+10,initial.top+10);pe('pointermove',160,90);pe('pointerup',160,90);
  const r0=panelHost.getBoundingClientRect();
  pe('pointerdown',r0.left+10,r0.top+10);pe('pointermove',r0.left-90,r0.top+60);pe('pointerup',r0.left-90,r0.top+60);
  const r1=panelHost.getBoundingClientRect();
  let savedPos=null;try{savedPos=JSON.parse(localStorage.getItem('kimi-lazy.userscript.pos.v1')||'null');}catch{}
  check('panel toggle drags freely and persists position',Math.round(r1.left-r0.left)===-100 && Math.round(r1.top-r0.top)===50 && savedPos&&typeof savedPos.fx==='number',{before:{l:r0.left,t:r0.top},after:{l:r1.left,t:r1.top},savedPos});
  pe('pointerdown',r1.left+10,r1.top+10);pe('pointermove',-5000,-5000);pe('pointerup',-5000,-5000);
  const r2=panelHost.getBoundingClientRect();
  check('panel drag clamps inside the viewport',r2.left>=3 && r2.top>=3 && r2.right<=innerWidth-3 && r2.bottom<=innerHeight-3,{l:r2.left,t:r2.top,r:r2.right,b:r2.bottom,vw:innerWidth,vh:innerHeight});
  tg.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));
  const suppressed=bodyEl.hidden;
  await new Promise(r=>setTimeout(r,400));tg.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));
  check('click after drag is suppressed, later click opens the panel',suppressed===true && bodyEl.hidden===false,{suppressed,hidden:bodyEl.hidden});
  tg.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));
  check('adapter reports no error',api.stats().error==='');
  window.fixtureTestsDone=true;
  return results;
};
