window.runFixtureTests = async (options = {}) => {
  window.fixtureTestsDone=false;
  const results=window.fixtureTestResults=[];
  const flush=async()=>{await fixture.tick();await new Promise(requestAnimationFrame);await fixture.tick();};
  const check=(name,ok,detail)=>{results.push({name,pass:!!ok,detail});if(!ok)throw new Error(JSON.stringify(results));};
  const scroll=document.querySelector('.chat-scroll');
  const api=__KIMI_LAZY__;
  const action=detail=>window.dispatchEvent(new CustomEvent('kimi-lazy-action',{detail}));
  api.configure({enabled:true,auto:false});action('recent');await flush();
  if (options.allowLate && fixtureInitialCounts.mounts > 200)
    check('Via late injection unmounts excess native leaves',document.querySelectorAll('pre').length===200 && fixtureCounts.unmounts>=1300,{initial:fixtureInitialCounts,now:{...fixtureCounts}});
  else check('first render mounts only the requested heavy leaves',fixtureInitialCounts.mounts===200 && fixtureInitialCounts.unmounts===0,fixtureInitialCounts);
  const main=()=>api.stats().groups.find(s=>s.name===(fixture.hwMode?'HistoryWindow':'ChatPane') && s.counts.some(c=>c.total===fixture.turns.value.length));
  check('latest 20 messages and per-message 20 blocks',main().counts[0].mounted===20 && document.querySelectorAll('pre').length===200,main().counts[0]);
  const old=document.querySelector('.kl-placeholder[data-turn-id="t1"]');
  old.click();await flush();
  check('restoring an old message uses native content',!!document.querySelector('.a-msg[data-turn-id="t1"]'),main().counts[0]);
  const head=document.querySelector('[data-turn-id="t1"] .ar-head');head.click();await flush();
  check('opening a 35-tool group mounts 20 tools',document.querySelectorAll('[data-turn-id="t1"] .ar-body pre').length===20,document.querySelectorAll('[data-turn-id="t1"] .ar-body pre').length);
  const block=document.querySelector('[data-turn-id="t1"] .ar-body .kl-placeholder');block.click();await flush();
  check('a tool block restores separately',document.querySelectorAll('[data-turn-id="t1"] .ar-body pre').length===21);
  const beforeClose=fixtureCounts.unmounts;head.click();await flush();
  check('closing a tool group unmounts its leaves',fixtureCounts.unmounts-beforeClose===21 && document.querySelectorAll('[data-turn-id="t1"] .ar-body pre').length===0);
  const restored=document.querySelector('[data-turn-id="t1"]');scroll.scrollTop=restored.offsetTop;await flush();
  api.sweep(Date.now()+600001);await flush();
  check('visible history survives timeout',!!document.querySelector('.a-msg[data-turn-id="t1"]'));
  scroll.scrollTop=scroll.scrollHeight;await flush();
  const before=fixtureCounts.unmounts;api.sweep(Date.now()+1200002);await flush();
  check('offscreen idle history is unmounted after ten minutes',!!document.querySelector('.kl-placeholder[data-turn-id="t1"]') && fixtureCounts.unmounts>before,fixtureCounts.unmounts-before);
  fixture.append();await flush();fixture.update();await flush();
  check('live turn limits old blocks and receives streaming delta',document.querySelectorAll('[data-turn-id="new1"] pre').length===20 && document.querySelector('[data-turn-id="new1"]').textContent.includes('STREAM DELTA') && fixture.turns.value.at(-1).blocks.length===41);
  fixture.active.value=false;await flush();action('all');await new Promise(r=>setTimeout(r,700));await flush();
  check('full history loading preserves virtualization',fixture.turns.value.length===52 && main().counts[0].mounted<52,main().counts[0]);
  const hash=JSON.stringify(fixture.turns.value);api.configure({enabled:false});await flush();
  check('disable restores all native content without altering data',document.querySelectorAll('.kl-placeholder').length===0 && document.querySelectorAll('.turn-anchor').length===52 && hash===JSON.stringify(fixture.turns.value));
  api.configure({enabled:true});await flush();fixture.switchSession();await flush();api.sweep();await flush();
  check('session change cleans old IDs and detached instances',document.querySelectorAll('[data-turn-id^="t"]').length===0 && main().counts[0].total===10 && api.stats().states<30,api.stats().states);
  let currentStatus;
  window.addEventListener('kimi-lazy-status',e=>{currentStatus=JSON.parse(e.detail);});
  action('status');
  const settings=document.getElementById('kimi-lazy-panel').shadowRoot;
  check('message mode keeps all four settings available',currentStatus.mode==='adapter' && currentStatus.unit==='turns' && !settings.getElementById('tuning').hidden && ['keep','blocks','idleMinutes','auto'].every(k=>!settings.getElementById(k).disabled));
  api.configure({keep:5,blocks:3,idleMinutes:1,auto:false});action('recent');await flush();
  check('changed message and block limits take effect',main().counts[0].mounted===5 && document.querySelectorAll('pre').length===9,{mounted:main().counts[0].mounted,leaves:document.querySelectorAll('pre').length});
  scroll.scrollTop=0;api.configure({auto:true});await flush();api.sweep();await flush();
  check('scrolling to sleeping history restores it automatically',!document.querySelector('.kl-placeholder[data-turn-id="b0"]'));
  scroll.scrollTop=scroll.scrollHeight;api.sweep(Date.now()+60001);await flush();
  check('changed idle timeout reclaims offscreen history',!!document.querySelector('.kl-placeholder[data-turn-id="b0"]'));
  api.configure({keep:20,blocks:20,idleMinutes:10,auto:false});await flush();
  const panelHost=document.getElementById('kimi-lazy-panel');
  const tg=panelHost.shadowRoot.getElementById('toggle'),bodyEl=panelHost.shadowRoot.getElementById('body');
  const pe=(type,x,y)=>tg.dispatchEvent(new PointerEvent(type,{pointerId:7,clientX:x,clientY:y,button:0,bubbles:true}));
  // Establish a known start even when a previous fixture run saved the top-left corner.
  const initial=panelHost.getBoundingClientRect();
  pe('pointerdown',initial.left+10,initial.top+10);pe('pointermove',160,90);pe('pointerup',160,90);
  const r0=panelHost.getBoundingClientRect();
  pe('pointerdown',r0.left+10,r0.top+10);pe('pointermove',r0.left-90,r0.top+60);pe('pointerup',r0.left-90,r0.top+60);
  const r1=panelHost.getBoundingClientRect();
  let savedPos=null;try{savedPos=JSON.parse(localStorage.getItem('kimi-lazy.userscript.pos.v1')||'null');}catch{}
  check('panel toggle drags freely and persists position',Math.round(r1.left-r0.left)===-100 && Math.round(r1.top-r0.top)===50 && savedPos&&typeof savedPos.fx==='number',{before:{l:r0.left,t:r0.top},after:{l:r1.left,t:r1.top},savedPos});
  pe('pointerdown',r1.left+10,r1.top+10);pe('pointermove',-5000,-5000);pe('pointerup',-5000,-5000);
  const r2=panelHost.getBoundingClientRect();
  check('panel drag clamps inside the viewport',r2.left>=3 && r2.top>=3 && r2.right<=innerWidth-3 && r2.bottom<=innerHeight-3,{l:r2.left,t:r2.top,r:r2.right,b:r2.bottom,vw:innerWidth,vh:innerHeight});
  tg.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));
  const suppressed=bodyEl.hidden;
  await new Promise(r=>setTimeout(r,400));tg.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));
  check('click after drag is suppressed, later click opens the panel',suppressed===true && bodyEl.hidden===false,{suppressed,hidden:bodyEl.hidden});
  tg.dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));
  check('adapter reports no error',api.stats().error==='');
  window.fixtureTestsDone=true;
  return results;
};
// ?hw=1 enables native windows explicitly; ?hw=off runs the full adapter suite.
window.runHwFixtureTests = async () => {
  window.fixtureTestsDone=false;
  const results=window.fixtureTestResults=[];
  const flush=async()=>{await fixture.tick();await new Promise(requestAnimationFrame);await fixture.tick();};
  const check=(name,ok,detail)=>{results.push({name,pass:!!ok,detail});if(!ok)throw new Error(JSON.stringify(results));};
  let lastStatus=null;
  window.addEventListener('kimi-lazy-status',e=>{try{lastStatus=JSON.parse(e.detail);}catch{}});
  const api=__KIMI_LAZY__;
  const statusNow=()=>{window.dispatchEvent(new CustomEvent('kimi-lazy-action',{detail:'status'}));return lastStatus;};
  api.configure({enabled:true,auto:false});await flush();
  check('HW: adapter attaches without error',api.stats().error==='',api.stats().error);
  check('HW: upstream turn window untouched, no turn placeholders',!document.querySelector('.kl-placeholder[data-turn-id]') && document.querySelectorAll('.a-msg,.u-bub').length===30,document.querySelectorAll('.a-msg,.u-bub').length);
  const first=document.querySelector('.a-msg');
  check('HW: message blocks windowed natively, adapter adds none',first.querySelectorAll('pre').length===20 && !first.querySelector('.kl-placeholder'),{pre:first.querySelectorAll('pre').length,ph:first.querySelectorAll('.kl-placeholder').length});
  const st=statusNow();
  check('HW: absent native fold bodies are not counted as recycled',!!st && st.mode==='native' && st.unit==='folds' && st.asleep===0 && st.mounted===0,st&&{unit:st.unit,mounted:st.mounted,asleep:st.asleep});
  const panel=document.getElementById('kimi-lazy-panel').shadowRoot;
  check('HW: native panel explains fold counts and hides inapplicable tuning',panel.getElementById('tuning').hidden && !panel.getElementById('native-hint').hidden && panel.getElementById('status').textContent.includes('原生按需渲染'));
  check('HW: collapsed tool bodies are unmounted',document.querySelectorAll('.ar-body pre').length===0,document.querySelectorAll('.ar-body pre').length);
  const head=document.querySelector('.ar-head');head.click();await flush();
  const openBody=document.querySelector('.ar-body.open');
  const st2=statusNow();
  check('HW: opened tool group is windowed natively, adapter adds no placeholders',!!openBody && openBody.querySelectorAll('pre').length===20 && openBody.querySelectorAll('.kl-placeholder').length===0 && st2.mounted===1 && st2.asleep===0,{pre:openBody&&openBody.querySelectorAll('pre').length,ph:openBody&&openBody.querySelectorAll('.kl-placeholder').length,st:st2&&{mounted:st2.mounted,asleep:st2.asleep}});
  head.click();await flush();
  const closed=statusNow();
  check('HW: closing a natively removed body clears its old mounted count',closed.mounted===0 && closed.asleep===0 && !document.querySelector('.ar-body'));
  head.click();await flush();
  api.configure({enabled:false});await flush();
  const restored=document.querySelector('.ar-body.open');
  check('HW: disable restores native rendering',!document.querySelector('.kl-placeholder') && !!restored && restored.querySelectorAll('pre').length===20 && api.stats().error==='',restored&&restored.querySelectorAll('pre').length);
  const disabled=statusNow();
  check('HW: disabled adapter clears its counters without re-enabling native tuning',disabled.mounted===0 && disabled.asleep===0 && panel.getElementById('tuning').hidden);
  window.fixtureTestsDone=true;
  return results;
};
